sudo: false
language: java
install: true
script:
  - mvn install
services:
  - docker
cache:
  directories:
  - "$HOME/.cache"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true

default_text_charset: 'utf-8'
